spring:
  profiles:
    active: dev
---
#development profile
spring:
  profiles: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.1.10.75:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:

    hibernate:
      ddl-auto: update
#      naming:
#        strategy: com.zcckj.rescue.entity.TableCreateStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
