spring:
  profiles:
    active: dev
---
#development profile
spring:
  profiles: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/ksoft
    driver-class-name: com.mysql.jdbc.Driver

#mvc
  mvc:
    view:
      suffix: .html


  redis:
    host: 171.188.0.166
    port: 6379
    database: 10


  jpa:
    hibernate:
#      ddl-auto: update
#      naming:
#        strategy: com.zcckj.rescue.entity.TableCreateStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true

mybatis:
  mapper-locations: classpath:mappers/*.xml

  config-location: classpath:page-config.xml